homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 28.3939
  longitude: -81.4216
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml
  
zone:
  - name: Home
    latitude: 28.375087
    longitude: -81.426789
    radius: 250
    icon: mdi:home

device_tracker:
  - platform: google_maps
    username: rafabene1006@gmail.com
    password: !secret gmaps

  - platform: automatic
    client_id: 223aa7a77accb58ff165
    secret: !secret automatic
    devices:
      - 2016 Jeep Wrangler Unlimited  
nest:
  client_id: aeeddc17-ffe2-4f40-ab39-bef918225853
  client_secret: !secret nest

camera:
  - platform: yi
    name: Living Room
    host: '192.168.0.3'
    password: !secret camera

  - platform: yi
    name: Bedroom
    host: '192.168.0.4'
    password: !secret camera

  - platform: yi
    name: Guest Room
    host: '192.168.0.5'
    password: !secret camera
    
media_player:
  - platform: spotify
    client_id: dd66dea98f574ce3b958bbec770dcc4b
    client_secret: !secret spotify

remote:
  - platform: harmony
    name: Watch TV
    host: 192.168.0.8
    activity: Watch TV

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
